#!/bin/sh
####################################################################
#
# define the following variables according to your needs
#
outdir= '/Users/vinhtran/Documents/GitHub/DFT/Energy-Lattice-Constant/Platinum'
pseudo_dir='/Users/vinhtran/Documents/GitHub/DFT/Energy-Lattice-Constant/Platinum'

# espresso_dir=top_directory_of_espresso_package
####################################################################

nk=6
#for smearing in gauss m-p m-v ; do

rm -f pt.scf.out pt.etot_vs_alat_hcp
touch pt.etot_vs_alat_hcp

#for degauss in 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.10 0.11 0.12 0.13 0.14 0.15; do
for alat in 7.0 7.1 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.0 8.1 ; do

cat > pt.scf.in << EOF
 &control
    prefix='pt',
    pseudo_dir = '/Users/vinhtran/Documents/GitHub/DFT/Energy-Lattice-Constant/Platinum',
    outdir='/Users/vinhtran/Documents/GitHub/DFT/Energy-Lattice-Constant/Platinum'
 /
 &system    
    ibrav=  4, celldm(1) = $alat, celldm(3) = 1.6, nat=  2, ntyp= 1,
    ecutwfc = 20.0, 
    occupations='smearing', smearing='gauss', degauss= 0.06
 /
 &electrons
 /
ATOMIC_SPECIES
 Pt  195.084 pt_pbe_v1.4.uspp.F.UPF
ATOMIC_POSITIONS (crystal)
 Pt 0.333333333 0.666666667 0.25
 Pt 0.666666667 0.333333333 0.75
K_POINTS automatic
$nk $nk $nk 1 1 1
EOF

pw.x -in pt.scf.in > pt.scf.out

grep -e 'lattice parameter' -e ! pt.scf.out | \
    awk '/lattice/{alat=$(NF-1)}/!/{print alat, $(NF-1)}' >> pt.etot_vs_alat_hcp

done

