#!/bin/sh
####################################################################
#
# define the following variables according to your needs
#
outdir= '/Users/vinhtran/Downloads/handson_pwscf/Aluminum'
pseudo_dir='/Users/vinhtran/Downloads/handson_pwscf/pseudo'

# espresso_dir=top_directory_of_espresso_package
####################################################################

nk=6
#for smearing in gauss m-p m-v ; do

rm -f al.test.out al.etot_vs_alat
#touch al.$smearing.$nk
touch al.etot_vs_alat

#for degauss in 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.10 0.11 0.12 0.13 0.14 0.15; do
for alat in 7.0 7.1 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.0 8.1 ; do

cat > al.test.in << EOF
 &control
    prefix='al',
    pseudo_dir = '/Users/vinhtran/Downloads/handson_pwscf/pseudo',
    outdir='/Users/vinhtran/Downloads/handson_pwscf/Aluminum'
 /
 &system    
    ibrav=  2, celldm(1) = $alat, nat=  1, ntyp= 1,
    ecutwfc =12.0, 
    occupations='smearing', smearing='gauss', degauss= 0.08
 /
 &electrons
 /
ATOMIC_SPECIES
 Al  26.98 Al.pz-vbc.UPF
ATOMIC_POSITIONS
 Al 0.00 0.00 0.00 
K_POINTS automatic
$nk $nk $nk 1 1 1
EOF

pw.x -in al.test.in > al.test.out

grep -e 'lattice parameter' -e ! al.test.out | \
    awk '/lattice/{alat=$(NF-1)}/!/{print alat, $(NF-1)}' >> al.etot_vs_alat

done

#mv al.gauss.$nk al.g.$nk
